name: Test
on: push
jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: "msys2 {0}"
    steps:
      - uses: spatial-model-editor/setup-ci@2024.10.29
      - run: which ccache && ccache -p
