name: Test
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-22.04"
            shell: "bash"
          - os: "ubuntu-22.04-arm"
            shell: "bash"
          - os: "macos-13"
            shell: "bash"
          - os: "macos-14"
            shell: "bash"
          - os: "windows-2022"
            shell: "msys2 {0}"
          - os: "windows-11-arm"
            shell: "msys2 {0}"
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: spatial-model-editor/setup-ci@main
      - run: ccache --version