name: Test
on: push
jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: "msys2 {0}"
    steps:
      - uses: spatial-model-editor/setup-ci@2025.01.02
      - run: cmake -E env "LANG=C" D:/a/_temp/msys64/ucrt64/bin/c++.exe -xc -c /dev/null -Wa,-v -o/dev/null
