name: Test
on: push
jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: "msys2 {0}"
    steps:
      - uses: spatial-model-editor/setup-ci@2025.01.02
      - uses: actions/checkout@v4
      - run: ./build.sh
